# Generated by Django 5.2.8 on 2025-11-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=200)),
                ('roll_number', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('year_of_study', models.IntegerField()),
                ('bio', models.TextField(blank=True)),
            ],
        ),
    ]
